runtime: php55
api_version: 1

env_variables:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "gamer-word"
  MYSQL_DSN: mysql:dbname=art;unix_socket=/cloudsql/web2assignment:us-central1:testsql
  
beta_settings:
  cloud_sql_instances: "web2assignment:us-central1:testsql"

handlers:
# Serve images as static resources
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  
# Serve images as static resources
- url: /(.+\.(htm|html))$
  static_files: \1
  upload: .+\.(htm|html)$
  application_readable: true

# Serve css as static
- url: /(.+\.(css))$
  static_files: \1
  upload: .+\.(css)$
  application_readable: true

#Serve JSON? Troubleshooting api errors
- url: /(.+\.(json))$
  static_files: \1
  upload: .+\.(json)$
  application_readable: true
  
# Serve php scripts
- url: /(.+\.php)$
  script: \1

# Serve php with "api" - need the regex for this
- url: /(.+api).+$
  static_files: \1
  upload: /(.+api)$
  application_readable: true

# Serve js scripts
- url: /(.+\.js)$
  script: \1
  
- url: /.*
  script: index.php